### ISSUE TITLE
Regular字重的【餒】有些问题

### ISSUE THREAD

**Issue by Beicxxxx** [lapomme/huayuan#1]
![image](https://user-images.githubusercontent.com/64363182/103434827-8c939700-4c41-11eb-926a-2de95a34d86e.png)

**Comment by Beicxxxx** [comment]
<img width="419" alt="屏幕截图 2021-01-01 145738" src="https://user-images.githubusercontent.com/64363182/103434838-b64cbe00-4c41-11eb-80f5-b9d8c27c5ec0.png">

**Comment by lapomme** [comment]
謝謝指出，下一版本會修正。

**Comment by lapomme** [comment]
v0.014裏已修改。
